""" binartrainer_ui.py --

 UI generated by GUI Builder Build 146 on 2025-12-20 17:04:13 from:
    C:/dev/bfwrechner/bfwrechner/binartrainer.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import tkinter as Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class Binartrainer(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization
        self.chk126 = Tkinter.Checkbutton(root,
            text = "",
        )
        self.chk64 = Tkinter.Checkbutton(root,
            text = "",
        )
        self.lbl126 = Tkinter.Label(root,
            text = 128,
        )
        self.lbl64 = Tkinter.Label(root,
            text = 64,
        )
        self.chk32 = Tkinter.Checkbutton(root,
            text = "",
        )
        self.lbl32 = Tkinter.Label(root,
            text = 32,
        )
        self.chk16 = Tkinter.Checkbutton(root,
            text = "",
        )
        self.lbl16 = Tkinter.Label(root,
            text = 16,
        )
        self._label_6 = Tkinter.Label(root,
            text = ".",
        )
        self.chk8 = Tkinter.Checkbutton(root,
            text = "",
        )
        self.chk4 = Tkinter.Checkbutton(root,
            text = "",
        )
        self.chk2 = Tkinter.Checkbutton(root,
            text = "",
        )
        self.chk1 = Tkinter.Checkbutton(root,
            text = "",
        )
        self.lbl8 = Tkinter.Label(root,
            text = 8,
        )
        self.lbl4 = Tkinter.Label(root,
            text = 4,
        )
        self.lbl2 = Tkinter.Label(root,
            text = 2,
        )
        self.lbl1 = Tkinter.Label(root,
            text = 1,
        )
        self.lbl_erg128 = Tkinter.Label(root,
            text = 0,
        )
        self.lbl_erg64 = Tkinter.Label(root,
            text = 0,
        )
        self.lbl_erg32 = Tkinter.Label(root,
            text = 0,
        )
        self.lbl_erg16 = Tkinter.Label(root,
            text = 0,
        )
        self.lbl_erg8 = Tkinter.Label(root,
            text = 0,
        )
        self.lbl_erg4 = Tkinter.Label(root,
            text = 0,
        )
        self.lbl_erg2 = Tkinter.Label(root,
            text = 0,
        )
        self.lbl_erg1 = Tkinter.Label(root,
            text = 0,
        )
        self.lbl_erg_dez = Tkinter.Label(root,
            font = "{MS Sans Serif} 12",
            text = 0,
        )
        self.lbl_erg_bin = Tkinter.Label(root,
            font = "{MS Sans Serif} 12",
            text = "0000.0000",
        )
        self._label_20 = Tkinter.Label(root,
            font = "Courier 20",
            text = u"Moerlis Bin\u00E4rtrainer",
        )

        # widget commands

        self.chk126.configure(
            command = self.chg_bin
        )
        self.chk64.configure(
            command = self.chg_bin
        )
        self.chk32.configure(
            command = self.chg_bin
        )
        self.chk16.configure(
            command = self.chg_bin
        )
        self.chk8.configure(
            command = self.chg_bin
        )
        self.chk4.configure(
            command = self.chg_bin
        )
        self.chk2.configure(
            command = self.chg_bin
        )
        self.chk1.configure(
            command = self.chg_bin
        )


        # Geometry Management
        self.chk126.grid(
            in_    = root,
            column = 2,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.chk64.grid(
            in_    = root,
            column = 3,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.lbl126.grid(
            in_    = root,
            column = 2,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.lbl64.grid(
            in_    = root,
            column = 3,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.chk32.grid(
            in_    = root,
            column = 4,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.lbl32.grid(
            in_    = root,
            column = 4,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.chk16.grid(
            in_    = root,
            column = 5,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.lbl16.grid(
            in_    = root,
            column = 5,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._label_6.grid(
            in_    = root,
            column = 6,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.chk8.grid(
            in_    = root,
            column = 7,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.chk4.grid(
            in_    = root,
            column = 8,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.chk2.grid(
            in_    = root,
            column = 9,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.chk1.grid(
            in_    = root,
            column = 10,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.lbl8.grid(
            in_    = root,
            column = 7,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.lbl4.grid(
            in_    = root,
            column = 8,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.lbl2.grid(
            in_    = root,
            column = 9,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.lbl1.grid(
            in_    = root,
            column = 10,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.lbl_erg128.grid(
            in_    = root,
            column = 2,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.lbl_erg64.grid(
            in_    = root,
            column = 3,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.lbl_erg32.grid(
            in_    = root,
            column = 4,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.lbl_erg16.grid(
            in_    = root,
            column = 5,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.lbl_erg8.grid(
            in_    = root,
            column = 7,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.lbl_erg4.grid(
            in_    = root,
            column = 8,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.lbl_erg2.grid(
            in_    = root,
            column = 9,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.lbl_erg1.grid(
            in_    = root,
            column = 10,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.lbl_erg_dez.grid(
            in_    = root,
            column = 11,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.lbl_erg_bin.grid(
            in_    = root,
            column = 11,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._label_20.grid(
            in_    = root,
            column = 2,
            row    = 1,
            columnspan = 9,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(2, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(3, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(4, weight = 0, minsize = 30, pad = 0)
        root.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        root.grid_columnconfigure(2, weight = 0, minsize = 27, pad = 0)
        root.grid_columnconfigure(3, weight = 0, minsize = 40, pad = 0)
        root.grid_columnconfigure(4, weight = 0, minsize = 40, pad = 0)
        root.grid_columnconfigure(5, weight = 0, minsize = 40, pad = 0)
        root.grid_columnconfigure(6, weight = 0, minsize = 10, pad = 0)
        root.grid_columnconfigure(7, weight = 0, minsize = 40, pad = 0)
        root.grid_columnconfigure(8, weight = 0, minsize = 40, pad = 0)
        root.grid_columnconfigure(9, weight = 0, minsize = 40, pad = 0)
        root.grid_columnconfigure(10, weight = 0, minsize = 40, pad = 0)
        root.grid_columnconfigure(11, weight = 0, minsize = 40, pad = 0)


