""" binartrainer.py --

 UI generated by GUI Builder Build 146 on 2025-12-20 17:04:13 from:
    C:/dev/bfwrechner/bfwrechner/binartrainer.ui
 This file is auto-generated.  Only the code within
    '# BEGIN USER CODE (global|class)'
    '# END USER CODE (global|class)'
 and code inside the callback subroutines will be round-tripped.
 The 'main' function is reserved.
"""

from Tkinter import *
from binartrainer_ui import Binartrainer

# BEGIN USER CODE global

# END USER CODE global

class CustomBinartrainer(Binartrainer):
    pass

    # BEGIN CALLBACK CODE
    # ONLY EDIT CODE INSIDE THE def FUNCTIONS.

    # _checkbutton_1_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _checkbutton_1_command(self, *args):
        pass

    # _checkbutton_2_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _checkbutton_2_command(self, *args):
        pass

    # _checkbutton_3_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _checkbutton_3_command(self, *args):
        pass

    # chk1_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def chk1_command(self, *args):
        pass

    # chk2_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def chk2_command(self, *args):
        pass

    # chk4_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def chk4_command(self, *args):
        pass

    # chk8_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def chk8_command(self, *args):
        pass

    # chk16_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def chk16_command(self, *args):
        pass

    # chk32_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def chk32_command(self, *args):
        pass

    # chk64_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def chk64_command(self, *args):
        pass

    # chk126_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def chk126_command(self, *args):
        pass

    # END CALLBACK CODE

    # BEGIN USER CODE class

    # END USER CODE class

def main():
    # Standalone Code Initialization
    # DO NOT EDIT
    try: userinit()
    except NameError: pass
    root = Tk()
    demo = CustomBinartrainer(root)
    root.title('binartrainer')
    try: run()
    except NameError: pass
    root.protocol('WM_DELETE_WINDOW', root.quit)
    root.mainloop()

if __name__ == '__main__': main()
